TestOnlineQuestion/Controllers/ManageContestController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TestOnlineQuestion.Models;
using TestOnlineQuestion.ViewModels;

namespace TestOnlineQuestion.Controllers
{
    public class ManageContestController : Controller
    {
        private WebDbContext db = new WebDbContext();

        // GET: ManageContest
        public ActionResult Index()
        {
            var contests = db.Contests.Include(c => c.Topic);
            return View(contests.ToList());
        }

        // GET: ManageContest/Create
        public ActionResult Create()
        {
            // Tạo một topic lưu trữ thông tin
            var topics = db.Topics
                .Where(t => t.State == true)  // tìm theo trạng thái
                .Select(t => new SelectListItem
                {
                    Value = t.Id.ToString(), // sủ dụng để lấy gí trị
                    Text = t.Name // sử dụng để hiển thị
                });

            ViewBag.TopicId = new SelectList(topics, "Value", "Text");
            return View();
        }

        // POST: ManageContest/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,TopicId,DifficultyLevel,QuestionCount")] Contest contest)
        {
            if (ModelState.IsValid)
            {
                db.Contests.Add(contest);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.TopicId = new SelectList(db.Topics, "Id", "Name", contest.TopicId);
            return View(contest);
        }

        // GET: ManageContest/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Contest contest = db.Contests.Find(id);
            if (contest == null)
            {
                return HttpNotFound();
            }
            // Lấy danh sách các chủ đề có trạng thái state = true
            var topics = db.Topics
                .Where(t => (bool)t.State)  // Lọc theo trạng thái
                .Select(t => new SelectListItem
                {
                    Value = t.Id.ToString(), // Giá trị để lưu
                    Text = t.Name // Hiển thị trong danh sách
                });
            ViewBag.TopicId = new SelectList(topics, "Value", "text", contest.TopicId);
            return View(contest);
        }

        // POST: ManageContest/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,TopicId,DifficultyLevel,QuestionCount")] Contest contest)
        {
            if (ModelState.IsValid)
            {
                db.Entry(contest).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.TopicId = new SelectList(db.Topics, "Id", "Name", contest.TopicId);
            return View(contest);
        }

        // GET: ManageContest/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Contest contest = db.Contests.Find(id);
            if (contest == null)
            {
                return HttpNotFound();
            }
            return View(contest);
        }

        // POST: ManageContest/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Contest contest = db.Contests.Find(id);
            db.Contests.Remove(contest);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult ManageContestQuestions(int id)
        {
            Contest contest = db.Contests.Find(id);
            if (contest == null)
            {
                return HttpNotFound();
            }

            ViewBag.QuestionCount = contest.QuestionCount;

            var relatedQuestions = db.Questions
                .Where(q => q.TopicId == contest.TopicId && q.DifficultyLevel == contest.DifficultyLevel)
                .ToList();

            ViewBag.ContestId = contest.Id;

            return View(relatedQuestions);
        }



        [HttpPost]
        public ActionResult AddQuestionsToContest(int ContestId, List<int> selectedQuestions)
        {
            Contest contest = db.Contests.Find(ContestId);

            if (contest == null)
            {
                return HttpNotFound();
            }

            try
            {
                // Xóa các câu hỏi đang tồn tại trong cuộc thi
                var existingContestQuestions = db.ContestQuestions
                    .Where(cq => cq.Idcontest == ContestId)
                    .ToList();

                db.ContestQuestions.RemoveRange(existingContestQuestions);

                // Tạo danh sách các ContestQuestion cần thêm vào cơ sở dữ liệu
                var contestQuestionsToAdd = new List<ContestQuestion>();

                foreach (int questionId in selectedQuestions)
                {
                    var question = db.Questions.Find(questionId);
                    if (question != null)
                    {
                        var contestQuestion = new ContestQuestion
                        {
                            Idcontest = ContestId,
                            IdQuestion = questionId,
                            DifficultyLevel = question.DifficultyLevel
                        };
                        contestQuestionsToAdd.Add(contestQuestion);
                    }
                }

                // Thêm tất cả các ContestQuestion đã chọn vào cơ sở dữ liệu
                db.ContestQuestions.AddRange(contestQuestionsToAdd);
                db.SaveChanges();

                TempData["SuccessMessage"] = "Các câu hỏi đã được thêm vào cuộc thi thành công!";
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = "Lỗi khi thêm câu hỏi vào cuộc thi: " + ex.Message;
            }

            return RedirectToAction("Index");
        }


        public ActionResult UserIndex(int? selectedTopicId)
        {
            // Tạo danh sách chủ đề
            var topics = db.Topics
                .Where(t => t.State == true)
                .Select(t => new SelectListItem
                {
                    Value = t.Id.ToString(),
                    Text = t.Name
                });

            ViewBag.TopicList = new SelectList(topics, "Value", "Text");

            // Lấy danh sách cuộc thi
            var contests = db.Contests.Include(c => c.Topic);

            // Lọc cuộc thi theo chủ đề được chọn (nếu có)
            if (selectedTopicId.HasValue && selectedTopicId > 0)
            {
                contests = contests.Where(c => c.TopicId == selectedTopicId.Value);
            }

            return View(contests.ToList());
        }

        public ActionResult ContestQuestions(int id)
        {
            var contestQuestions = db.ContestQuestions
                .Where(cq => cq.Idcontest == id)
                .Select(cq => new QuestionDTO
                {
                    Id = cq.IdQuestion,
                    QuestionText = cq.Question.QuestionText,
                    Answer1 = cq.Question.Answer1,
                    Answer2 = cq.Question.Answer2,
                    Answer3 = cq.Question.Answer3,
                    Answer4 = cq.Question.Answer4,
                    SelectedAnswer = 0 // Khởi tạo lựa chọn mặc định là 0 (chưa chọn)
                })
                .ToList();

            return View(contestQuestions);
        }
        private int CalculateCorrectAnswers(List<QuestionDTO> userAnswers, int contestId)
        {
            int correctAnswersCount = 0;

            var correctAnswers = db.ContestQuestions
                .Where(cq => cq.Idcontest == contestId)
                .Select(cq => new { QuestionId = cq.IdQuestion, CorrectAnswer = cq.Question.CorrectAnswer })
                .ToList();

            foreach (var answer in userAnswers)
            {
                var correctAnswer = correctAnswers.FirstOrDefault(ca => ca.QuestionId == answer.Id);
                if (correctAnswer != null && correctAnswer.CorrectAnswer == answer.SelectedAnswer)
                {
                    correctAnswersCount++;
                }
            }

            return correctAnswersCount;
        }

        [HttpPost]
        public ActionResult SubmitContestAnswers(int ContestId, List<QuestionDTO> userAnswers)
        {
            int correctAnswersCount = CalculateCorrectAnswers(userAnswers, ContestId);
            ViewBag.CorrectAnswersCount = correctAnswersCount;

            // Retrieve contest questions to display the full details in the "ContestResults" view
            var contestQuestions = db.ContestQuestions
                .Where(cq => cq.Idcontest == ContestId)
                .Select(cq => new QuestionDTO
                {
                    Id = cq.IdQuestion,
                    QuestionText = cq.Question.QuestionText,
                    Answer1 = cq.Question.Answer1,
                    Answer2 = cq.Question.Answer2,
                    Answer3 = cq.Question.Answer3,
                    Answer4 = cq.Question.Answer4,
                    SelectedAnswer = 0 // Khởi tạo lựa chọn mặc định là 0 (chưa chọn)
                })
                .ToList();

            return View("ContestResults", contestQuestions);
        }



        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TestOnlineQuestion/Controllers/QuestionController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TestOnlineQuestion.Models;

namespace TestOnlineQuestion.Controllers
{
    public class QuestionController : Controller
    {
        private WebDbContext db = new WebDbContext();

        // Phương thức hành động để hiển thị danh sách câu hỏi
        public ActionResult Index()
        {
            var questions = db.Questions.ToList();
            return View(questions);
        }

        public ActionResult Create()
        {
           //Tạo một topic lưu trữ thông tin
            var topics = db.Topics
                .Where(t => t.State == true)  // tìm theo trạng thái
                .Select(t => new SelectListItem
                {
                    Value = t.Id.ToString(), // sủ dụng để lấy gí trị 
                    Text = t.Name // sử dụng để hiển thị
                });

            ViewBag.TopicId = new SelectList(topics, "Value", "Text");

            return View();
        }


        // Phương thức hành động xử lý yêu cầu POST để tạo câu hỏi mới
        [HttpPost]
        public ActionResult Create(Question question)
        {
            if (ModelState.IsValid)
            {
                db.Questions.Add(question);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(question);
        }

        // Phương thức hành động để hiển thị form chỉnh sửa câu hỏi
        public ActionResult Edit(int id)
        {
            // Lấy câu hỏi theo id
            var question = db.Questions.Find(id);

            // Lấy danh sách các chủ đề có trạng thái state = true
            var topics = db.Topics
                .Where(t => (bool)t.State)  // Lọc theo trạng thái
                .Select(t => new SelectListItem
                {
                    Value = t.Id.ToString(), // Giá trị để lưu
                    Text = t.Name // Hiển thị trong danh sách
                });

            // Tạo một SelectList từ danh sách chủ đề và chọn giá trị cho câu hỏi hiện tại
            ViewBag.TopicId = new SelectList(topics, "Value", "Text", question.TopicId);

            if (question == null)
            {
                return HttpNotFound();
            }

            return View(question);
        }


        // Phương thức hành động xử lý yêu cầu POST để cập nhật câu hỏi
        [HttpPost]
        public ActionResult Edit(Question question)
        {
            if (ModelState.IsValid)
            {
                db.Entry(question).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(question);
        }

        // Phương thức hành động hiển thị form xóa câu hỏi
        public ActionResult Delete(int id)
        {
            var question = db.Questions.Find(id);
            if (question == null)
            {
                return HttpNotFound();
            }
            return View(question);
        }

        // Phương thức hành động xử lý yêu cầu POST để xóa câu hỏi
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            var question = db.Questions.Find(id);
            db.Questions.Remove(question);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

TestOnlineQuestion/Controllers/TopicController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TestOnlineQuestion.Models;

namespace TestOnlineQuestion.Controllers
{
    public class TopicController : Controller
    {
        private WebDbContext db = new WebDbContext();

        public ActionResult Index()
        {
            var topics = db.Topics.Where(x => x.State == true).ToList();
            return View(topics);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Topic topic)
        {
            if (ModelState.IsValid)
            {
                topic.State = true;
                db.Topics.Add(topic);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(topic);
        }

        public ActionResult Edit(int id)
        {
            Topic topic = db.Topics.Find(id);
            if (topic == null)
            {
                return HttpNotFound();
            }
            return View(topic);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Topic topic)
        {
            if (ModelState.IsValid)
            {
                db.Entry(topic).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(topic);
        }

        public ActionResult Delete(int id)
        {
            Topic topic = db.Topics.Find(id);
            if (topic == null)
            {
                return HttpNotFound();
            }
            return View(topic);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Topic topic = db.Topics.Find(id);
            topic.State = false;
            //db.Topics.Remove(topic);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TestOnlineQuestion/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Home", "AdminIndex", "Account", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Tài khoản", "AccountInfoAdmin", "Account", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Quản lý tài khoản", "ManageUsers", "Account", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Chủ đề", "Index", "Topic", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Cuộc thi", "Index", "ManageContest", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Câu hỏi", "Index", "Question", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Đăng xuất", "Logout", "Account", new { area = "" }, new { @class = "nav-link" })</li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

TestOnlineQuestion/Views/Shared/_DefaultLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My Quiz Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("Quiz Application", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                        <li>@Html.ActionLink("Home", "UserIndex", "Account", new { area = "" }, new { @class = "nav-link" })</li>
                        <li>@Html.ActionLink("Tài khoản", "AccountInfoUser", "Account", new { area = "" }, new { @class = "nav-link" })</li>
                        <li>@Html.ActionLink("Cuộc thi sinh viên", "UserIndex", "ManageContest", new { area = "" }, new { @class = "nav-link" })</li>
                        <li>@Html.ActionLink("Đăng xuất", "Logout", "Account", new { area = "" }, new { @class = "nav-link" })</li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

TestOnlineQuestion/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <style>
        body {
            background-image: url('../../content/image/quiz_800x450.jpg');
            background-size: cover;
            background-repeat: no-repeat;
        }
    </style>
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("Quiz Application", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    @* <li>@Html.ActionLink("Tài khoản", "AccountInfo", "Account", new { area = "" }, new { @class = "nav-link" })</li>
                       <li>@Html.ActionLink("Quản lý tài khoản", "ManageUsers", "Account", new { area = "" }, new { @class = "nav-link" })</li>
                       <li>@Html.ActionLink("Chủ đề", "Index", "Topic", new { area = "" }, new { @class = "nav-link" })</li>
                       <li>@Html.ActionLink("Cuộc thi", "Index", "ManageContest", new { area = "" }, new { @class = "nav-link" })</li>
                       <li>@Html.ActionLink("Câu hỏi", "Index", "Question", new { area = "" }, new { @class = "nav-link" })</li>
                       <li>@Html.ActionLink("Đăng xuất", "Logout", "Account", new { area = "" }, new { @class = "nav-link" })</li>*@
                    <li>@Html.ActionLink("Sign In", "UserLogin", "Account", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Sign Up", "Register", "Account", new { area = "" }, new { @class = "nav-link" })</li>              
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>